FROM demoregistry.dataman-inc.com/library/centos7-base:latest

MAINTAINER Zhongqiang Dou zqdou@dataman-inc.com

RUN mkdir /dataman /dataman/rules /dataman/exprs

ADD bin/mola /dataman/mola
ADD frontend /dataman/frontend
ADD env_file.template /dataman/env_file
ADD config/exprs/* /dataman/exprs/
ADD config/mola-conf.template.yaml /dataman/labels-define.yaml

WORKDIR dataman

EXPOSE 5098

ENTRYPOINT ["./mola"]
