---
name: "CPU使用率"
aggregation: "avg"
function: "irate"
metric: "container_cpu_usage_seconds_total"
filter:
  cluster: ""
  user: ""
  app: ""
  slot: ""
  task: ""
  fixed: "id=~'/docker/.*', name=~'mesos.*'"
by:
  cluster: ""
  user: ""
  app: ""
  task: ""
