---
name: "CPU使用率"
aggregation: "avg"
function: "irate"
metric: "container_cpu_usage_seconds_total"
filter:
  app: "container_label_DM_APP_ID='%s'"
  slot: "container_label_DM_SLOT_INDEX='%s'"
  slotid: "container_label_DM_SLOT_ID='%s'"
  fixed: "id=~'/docker/.*', name=~'mesos.*'"
by:
  - "container_label_DM_APP_ID"
  - "container_label_DM_SLOT_INDEX"
