---
name: "负载均衡Http总请求数"
aggregation: "sum"
function: ""
metric: "haproxy_frontend_http_requests_total"
filter:
  cluster: "container_label_VCLUSTE='%s'"
  user: ""
  app: "container_label_APP_ID='%s'"
  task: "container_env_mesos_task_id='%s'"
  fixed: "frontend!='stats'"
by:
  - "container_label_VCLUSTER"
  - "container_label_APP_ID"
  - "container_env_mesos_task_id"
