---
name: "内存使用字节数"
aggregation: "sum"
function: ""
metric: "container_memory_usage_bytes"
filter:
  cluster: ""
  user: ""
  app: ""
  slot: ""
  task: ""
  fixed: ""
by:
  cluster: ""
  user: ""
  app: ""
  task: ""
