---
name: "Memory_Limit_Bytes"
aggregation: "sum"
function: ""
metric: "container_spec_memory_limit_bytes"
filter:
  app: "container_label_DM_APP_ID='%s'"
  slot: "container_label_DM_SLOT_INDEX='%s'"
  slotid: "container_label_DM_SLOT_ID='%s'"
  fixed: "id=~'/docker/.*', name=~'mesos.*'"
by:
  - "container_label_DM_APP_ID"
  - "container_label_DM_SLOT_INDEX"
