---
name: "mem_usage"
aggregation: ""
function: ""
metric: "container_memory_usage_bytes"
filter:
  cluster: "container_label_CLUSTER='%s'"
  user: "container_label_USER='%s'"
  app: "container_label_APP='%s'"
  task: "container_label_SLOT='%s'"
  fixed: "id=~'/docker/.*', name=~'mesos.*'"
by:
  - "container_label_CLUSTER"
  - "container_label_USER"
  - "container_label_APP"
  - "container_label_SLOT"
