---
name: "内存分配字节数"
aggregation: "sum"
function: ""
metric: "container_spec_memory_limit_bytes"
filter:
  cluster: "container_label_VCLUSTER='%s'"
  user: ""
  app: "container_label_APP_ID='%s'"
  task: "container_env_mesos_task_id='%s'"
  fixed: "id=~'/docker/.*', name=~'mesos.*'"
by:
  - "container_label_VCLUSTER"
  - "container_label_APP_ID"
  - "container_env_mesos_task_id"
