---
name: "内存使用字节数"
aggregation: "sum"
function: ""
metric: "container_memory_usage_bytes"
filter:
  app: "container_label_DM_APP_ID='%s'"
  slot: "container_label_DM_SLOT_INDEX='%s'"
  slotid: "container_label_DM_SLOT_ID='%s'"
  fixed: "id=~'/docker/.*', name=~'mesos.*'"
by:
  - "container_label_DM_APP_ID"
  - "container_label_DM_SLOT_INDEX"
