---
name: "Tomcat当前线程数"
aggregation: "sum"
function: ""
metric: "tomcat_threadpool_currentthreadcount"
filter:
  cluster: "container_label_VCLUSTER='%s'"
  user: ""
  app: "container_label_APP_ID='%s'"
  task: "container_env_mesos_task_id='%s'"
  fixed: ""
by:
  - "container_label_VCLUSTER"
  - "container_label_APP_ID"
  - "container_env_mesos_task_id"
