agent:
  image: demoregistry.dataman-inc.com/shurenyun/centos7-log-agent:v1.1
  cpu_quota: 1000
  environment:
   - OUTPUT=tcp://192.168.1.74:5044
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock:ro
   - /data/:/data/:ro
   - /usr/share/:/bin/data/
   - /etc/localtime:/etc/localtime:ro
  restart: always
